### ISSUE TITLE
有系统镜像和安装教程分享吗？

### ISSUE THREAD

**Issue by chca2** [Xmingbai/Minisforum-UM560XT-APU-Hackintosh#2]

**Comment by markvtp** [comment]
https://mp.weixin.qq.com/s?__biz=MzU3MjAwMjIzMw==&mid=2247488238&idx=1&sn=8443168d34e83d22b8e4f9791d22311b&chksm=fcd6c838cba1412e32ed077b9b1e42b7937df91eef2a1ba40584ea94dff94080fb42bbdb4c9c&scene=126&sessionid=1689999243#rd



https://mp.weixin.qq.com/s/KJ4R-uXFif9nmHQTgX_Mfg
